version: '3.1'

services:
  app:
    build: .
    restart: always
    ports:
      - "5005:5005"
    voluve:
      - ./db:/db
    environment:
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}

